const CHEFS=[
{id:1,name:'فاطمة الزهراء',prefix:'أمّي',initial:'ف',area:'المعاريف',specialty:'كسكس بالخضر السبع · طاجين الدجاج',rating:'4.9',status:'available',dishes:[['كسكس بالخضر السبع','45 درهم'],['طاجين الدجاج بالزيتون','52 درهم'],['حريرة مغربية','20 درهم']]},
{id:2,name:'خديجة',prefix:'أمّي',initial:'خ',area:'بوركون',specialty:'رفيسة · بسطيلة · حلويات مغربية',rating:'4.8',status:'available',dishes:[['رفيسة بالدجاج البلدي','55 درهم'],['بسطيلة الدجاج','65 درهم'],['سلو منزلي','28 درهم']]},
{id:3,name:'مريم',prefix:'أمّي',initial:'م',area:'عين السبع',specialty:'طواجن · أطباق شعبية · خبز الدار',rating:'4.9',status:'busy',dishes:[['طاجين اللحم بالبرقوق','68 درهم'],['لوبيا على الطريقة المغربية','30 درهم'],['خبز الدار','8 دراهم']]}
];
const citySelect=document.getElementById('citySelect');
const comingModal=document.getElementById('comingModal');
const orderModal=document.getElementById('orderModal');
const joinModal=document.getElementById('joinModal');
const toast=document.getElementById('toast');
let activeChef=null,activeDish=null,joinGender='female';
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0)}
function showToast(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function openModal(el){el.classList.add('open');el.setAttribute('aria-hidden','false')}
function closeModal(el){el.classList.remove('open');el.setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.closest('.modal'))));
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m)}));
document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>showScreen('home')));
function renderChefs(){const grid=document.getElementById('chefGrid');grid.innerHTML=CHEFS.map(c=>`<article class="chef-card" data-chef="${c.id}"><div class="avatar">${c.initial}</div><div class="chef-main"><div class="chef-name">${c.prefix} ${c.name}</div><div class="chef-specialty">${c.specialty}</div><div class="chef-meta"><span>${c.area}</span><span>★ ${c.rating}</span><span class="status ${c.status}">${c.status==='available'?'متاحة الآن':'مشغولة'}</span></div></div><div class="arrow">←</div></article>`).join('');grid.querySelectorAll('[data-chef]').forEach(el=>el.addEventListener('click',()=>openChef(Number(el.dataset.chef))))}
function openChef(id){activeChef=CHEFS.find(c=>c.id===id);activeDish=null;document.getElementById('orderChefName').textContent=`${activeChef.prefix} ${activeChef.name}`;document.getElementById('orderChefArea').textContent=activeChef.area;document.getElementById('orderAvatar').textContent=activeChef.initial;const list=document.getElementById('dishList');list.innerHTML=activeChef.dishes.map((d,i)=>`<button class="dish-option" data-dish="${i}"><span>${d[0]}</span><strong>${d[1]}</strong></button>`).join('');list.querySelectorAll('[data-dish]').forEach(b=>b.addEventListener('click',()=>{list.querySelectorAll('.dish-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');activeDish=activeChef.dishes[Number(b.dataset.dish)]}));openModal(orderModal)}
document.getElementById('discoverBtn').addEventListener('click',()=>{const city=citySelect.value;if(!city){showToast('اختر المدينة أولًا');return}if(city!=='casablanca'){const name=citySelect.options[citySelect.selectedIndex].text.split(' — ')[0];document.getElementById('comingTitle').textContent=`قريبًا في ${name}`;openModal(comingModal);return}document.getElementById('cityTitle').textContent='الدار البيضاء';renderChefs();showScreen('chefs')});
document.getElementById('submitOrderBtn').addEventListener('click',()=>{const name=document.getElementById('customerName').value.trim(),phone=document.getElementById('customerPhone').value.trim(),area=document.getElementById('customerArea').value.trim();if(!activeDish){showToast('اختر طبقًا أولًا');return}if(!name||!phone||!area){showToast('أكمل معلومات الطلب');return}const ref='OF-'+Math.floor(10000+Math.random()*90000);closeModal(orderModal);showToast(`تم تسجيل الطلب ${ref}`)});
document.querySelectorAll('[data-open-join]').forEach(b=>b.addEventListener('click',()=>openModal(joinModal)));
document.querySelectorAll('.gender').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.gender').forEach(x=>x.classList.remove('active'));b.classList.add('active');joinGender=b.dataset.gender;updateNamePreview()}));
function cleanName(value){return value.replace(/^(أمّي|امي|أمي|عمّي|عمي|Ommi|Oncle)\s*/i,'').trim()}
function updateNamePreview(){const input=document.getElementById('joinName');const cleaned=cleanName(input.value);if(input.value!==cleaned)input.value=cleaned;document.getElementById('namePreview').textContent=`${joinGender==='female'?'أمّي':'عمّي'} ${cleaned||(joinGender==='female'?'فاطمة':'كريم')}`}
document.getElementById('joinName').addEventListener('input',updateNamePreview);
document.getElementById('submitJoinBtn').addEventListener('click',()=>{const name=cleanName(document.getElementById('joinName').value),phone=document.getElementById('joinPhone').value.trim(),specialty=document.getElementById('joinSpecialty').value.trim();if(!name||!phone||!specialty){showToast('أكمل الاسم والهاتف والتخصص');return}closeModal(joinModal);showToast('تم إرسال طلب الانضمام للمراجعة')});