/* Simple launch: one meal creation screen, three kitchen actions, no billing UI. */
'use strict';
document.getElementById('showDiscoveryBtn').onclick=async()=>{showScreen('chefs');await loadChefs();};
document.querySelector('#home .home-form').prepend(document.querySelector('#home .home-paths'));
document.querySelector('#home .chef-invite strong').textContent='حوّلي مهارتك في الطبخ إلى عمل من بيتك.';
document.querySelector('#home .chef-invite p').textContent='أضيفي وجبتك وموعدها، واستقبلي طلبات الجيران.';
document.getElementById('chefLoginBtn')?.remove();
const genderMale=g=>['m','male','ذكر'].includes(String(g||'').toLowerCase());
prefix=g=>genderMale(g)?'عمّي':'أمّي';
const simpleDashboardBase=renderKitchenDashboard;
renderKitchenDashboard=function(c){const screen=simpleDashboardBase(c),box=screen.querySelector('.kitchen-builder');box.querySelector('.builder-step')?.remove();box.querySelector('#myKitchenDishes').hidden=true;box.querySelector('.builder-actions').hidden=true;screen.querySelector('.welcome-kitchen > span').textContent='تم ربط مطبخ منزلك بالمنصة';return screen;};
mountMealDashboard=function(c){const dash=document.getElementById('chefKitchenDashboard'),box=dash.querySelector('.kitchen-builder');let actions=document.getElementById('mealActions');if(!actions){actions=document.createElement('div');actions.id='mealActions';actions.className='simple-kitchen-actions';box.append(actions);}actions.replaceChildren(mealAction('＋ إضافة وجبة',()=>openMealOfferForm(c)),mealAction('وجباتي وطلباتي',openKitchenWork),mealAction('بيانات مطبخي',()=>openKitchenSettings(c)));actions.firstChild.className='primary';};
async function openKitchenWork(){const c=await restoreChefSession(false);if(!c)throw Error('ادخل إلى مطبخك مجددًا.');const screen=mealPanel('kitchenWork','وجباتي وطلباتي'),box=screen.querySelector('.meal-content');box.replaceChildren(mealAction('الطلبات الواردة',openChefMealOrders),mealAction('الوجبات المعروضة',openMyMealOffers));screen.querySelector('.back').onclick=()=>openKitchenDashboard(c);showScreen(screen.id);await openChefMealOrders();document.querySelector('#chefMealOrders .meal-content').prepend(mealAction('وجباتي المعروضة',openMyMealOffers));}
async function openKitchenSettings(c){const screen=mealPanel('kitchenSettings','بيانات مطبخي'),box=screen.querySelector('.meal-content');box.innerHTML=`<h1>${prefix(c.gender)} ${escapeHtml(c.name)}</h1><p>${escapeHtml(c.area||'')} · الدار البيضاء</p><p id="kitchenLocationStatus">جاري تحميل الموقع…</p>`;screen.querySelector('.back').onclick=()=>openKitchenDashboard(c);box.append(mealAction('تحديد موقع مطبخي',async()=>{await pickLocation(true,null,saveKitchenPoint);}),mealAction('تعديل الأطباق وأيام العمل',()=>openKitchenEditor(c,'edit')),mealAction('تسجيل الخروج',async()=>{await mealRpc('chef_logout',{p_session_token:chefSessionToken});localStorage.removeItem(CHEF_SESSION_KEY);chefSessionToken='';currentChefId=null;showScreen('home');}));showScreen(screen.id);try{const p=await mealRpc('chef_location',{p_session_token:chefSessionToken});document.getElementById('kitchenLocationStatus').textContent=p?'موقعك محفوظ. يظهر للزبائن بشكل تقريبي لحماية منزلك.':'حدد الموقع ليجدك الزبائن القريبون. يمكنك فعل ذلك لاحقًا.';if(p){box.append(mealAction('تعديل الموقع',()=>pickLocation(true,[Number(p.lat),Number(p.lng)],saveKitchenPoint)),mealAction('حذف الموقع المحفوظ',async()=>{await mealRpc('chef_location',{p_session_token:chefSessionToken,p_remove:true});await openKitchenSettings(c);}));}}catch{document.getElementById('kitchenLocationStatus').textContent='تعذر تحميل الموقع. يمكنك الاستمرار وتحديده لاحقًا.';}}
async function saveKitchenPoint(p){await mealRpc('chef_location',{p_session_token:chefSessionToken,p_lat:p[0],p_lng:p[1]});const status=document.getElementById('kitchenLocationStatus');if(status)status.textContent='تم حفظ الموقع. يظهر للزبائن بشكل تقريبي.';showToast('تم حفظ موقع مطبخك.');}
function localMealValue(date){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Casablanca',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
openMealOfferForm=async function(){const c=await restoreChefSession(false);if(!c)throw Error('ادخل إلى مطبخك مجددًا.');const screen=mealPanel('mealOfferEditor','إضافة وجبة'),box=screen.querySelector('.meal-content'),dishes=normaliseDishes(c.dishes),request=crypto.randomUUID();screen.querySelector('.back').onclick=()=>openKitchenDashboard(c);
 const specialties=[...document.getElementById('builderSpecialty').options].filter(o=>o.value);
 box.innerHTML=`<form id="mealOfferForm" class="meal-form"><h1>وجبة من مطبخك</h1><label>نوع الأطباق<select name="specialty" class="field" required><option value="">اختيار النوع</option>${specialties.map(o=>`<option ${o.value===c.specialty?'selected':''}>${escapeHtml(o.value)}</option>`).join('')}</select></label>${dishes.length?`<label>استخدام طبق سابق (اختياري)<select name="saved" class="field"><option value="">طبق جديد</option>${dishes.map((d,i)=>`<option value="${i}">${escapeHtml(d.name)}</option>`).join('')}</select></label>`:''}<label>اسم الوجبة<input name="dish_name" class="field" required maxlength="150" placeholder="مثال: كسكس بالخضر واللحم"></label><label>ثمن الحصة بالدرهم<input name="price" class="field" type="number" min="1" max="10000" step="0.01" inputmode="decimal" required></label><label>صورة الوجبة (اختياري)<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" class="field"></label><img id="mealPhotoPreview" alt="معاينة صورة الوجبة" hidden><label>الحصة تكفي<input name="portion" class="field" required maxlength="300" value="شخصًا واحدًا"></label><label>المكونات الرئيسية<textarea name="ingredients" class="field" required maxlength="2000" placeholder="مثال: سميد، خضر، لحم"></textarea></label><label>عدد الحصص المتاحة<input name="quantity" type="number" class="field" min="1" max="500" required inputmode="numeric"></label><label>متى تكون الوجبة جاهزة؟<input name="ready_at" type="datetime-local" class="field" required></label><label>استقبال الطلبات وقبولها حتى<input name="order_until" type="datetime-local" class="field" required></label><small>المواعيد بتوقيت المغرب.</small><label>طريقة الاستلام<select name="fulfilment_type" class="field"><option value="pickup">الاستلام من المطبخ</option><option value="delivery">التوصيل</option><option value="both">الاستلام أو التوصيل</option></select></label><div data-pickup><label>عنوان الاستلام<input name="pickup_instructions" class="field" minlength="5" maxlength="1000"></label><small>يظهر فقط للزبون بعد قبول طلبه.</small></div><div data-delivery hidden><label>أحياء التوصيل، كل حي في سطر<textarea name="delivery_areas" class="field" maxlength="2000">${escapeHtml(c.area||'')}</textarea></label><label>ثمن التوصيل بالدرهم<input name="delivery_fee" type="number" min="0" max="1000" step="0.01" class="field" value="0"></label></div><button type="submit" class="primary full">عرض الوجبة لاستقبال الطلبات</button><p role="status" id="mealFormStatus"></p></form>`;
 const form=box.querySelector('form');let savedImage=null,uploaded=null,objectUrl=null;const preview=box.querySelector('#mealPhotoPreview');
 if(form.elements.saved)form.elements.saved.onchange=()=>{const d=dishes[Number(form.elements.saved.value)];if(form.elements.saved.value===''){form.elements.dish_name.value='';form.elements.price.value='';savedImage=null;preview.hidden=true;return;}form.elements.dish_name.value=d.name;form.elements.price.value=d.price;savedImage=safeImageUrl(d.image_url)||null;preview.hidden=!savedImage;if(savedImage)preview.src=savedImage;};
 form.elements.photo.onchange=()=>{uploaded=null;const f=form.elements.photo.files[0];if(!f)return;if(f.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type)){form.elements.photo.value='';showToast('اختر صورة لا تتجاوز 5 ميغابايت.');return;}if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(f);preview.src=objectUrl;preview.hidden=false;};
 const mode=form.elements.fulfilment_type;const sync=()=>{const delivery=mode.value!=='pickup',pickup=mode.value!=='delivery';box.querySelector('[data-delivery]').hidden=!delivery;box.querySelector('[data-pickup]').hidden=!pickup;form.elements.delivery_areas.required=delivery;form.elements.pickup_instructions.required=pickup;};mode.onchange=sync;sync();
 form.elements.ready_at.min=localMealValue(new Date());form.elements.order_until.min=localMealValue(new Date());
 form.onsubmit=e=>{e.preventDefault();if(!form.reportValidity())return;mealBusy(form.querySelector('[type=submit]'),async()=>{const p=Object.fromEntries(new FormData(form));p.ready_at=mealLocalToISO(p.ready_at);p.order_until=mealLocalToISO(p.order_until);if(new Date(p.order_until)<=new Date()||new Date(p.order_until)>=new Date(p.ready_at))throw Error('آخر أجل للطلب يجب أن يكون قبل الجاهزية وفي المستقبل.');p.delivery_areas=[...new Set(String(p.delivery_areas).split('\n').map(x=>x.trim()).filter(Boolean))];const photo=form.elements.photo.files[0];if(photo&&!uploaded)uploaded=await uploadImageSecure(photo);const dish={name:p.dish_name.trim(),price:Number(p.price),image_url:uploaded||savedImage};await mealRpc('chef_publish_meal',{p_session_token:chefSessionToken,p_dish:dish,p_offer:p,p_request:request});if(objectUrl)URL.revokeObjectURL(objectUrl);showToast('وجبتك معروضة الآن.');await openMyMealOffers();});};showScreen(screen.id);
};
// Keep saved recipes tucked into settings; the main path never requires saving twice.
const simpleOffersBase=openMyMealOffers;openMyMealOffers=async function(){await simpleOffersBase();document.querySelector('#myMealOffers .meal-content').prepend(mealAction('＋ إضافة وجبة',openMealOfferForm),mealAction('طلبات مطبخي',openChefMealOrders));};
// Accessible quantity controls do not replace server-side capacity checks.
const qty=document.getElementById('mealQuantity'),stepper=document.createElement('div');stepper.className='quantity-stepper';qty.parentNode.insertBefore(stepper,qty);const less=mealAction('−',()=>{}),more=mealAction('+',()=>{});less.setAttribute('aria-label','تقليل الحصص');more.setAttribute('aria-label','زيادة الحصص');less.onclick=()=>{qty.value=Math.max(1,Number(qty.value)-1);updateMealTotal();};more.onclick=()=>{qty.value=Math.min(Number(qty.max),Number(qty.value)+1);updateMealTotal();};stepper.append(less,qty,more);
document.getElementById('customerPhone').inputMode='tel';document.getElementById('customerPhone').autocomplete='tel-national';document.getElementById('customerName').autocomplete='given-name';
// Neutral wording works for both male and female cooks without guessing from names.
document.querySelector('#buildKitchen .join-note')?.remove();
// Share a kitchen, never a private order or chef session.
async function shareKitchen(c){const url=new URL(location.origin+location.pathname);url.hash='kitchen='+c.id;const data={title:`${prefix(c.gender)} ${c.name} — أمّي فود`,text:'أطباق مغربية بطعم البيت، من مطبخي إلى بيتك.',url:url.href};try{if(navigator.share){await navigator.share(data);return;}await navigator.clipboard.writeText(url.href);showToast('تم نسخ رابط مطبخك.');}catch(e){if(e.name==='AbortError')return;const box=document.querySelector('#kitchenSettings .meal-content');let input=box.querySelector('[data-kitchen-link]');if(!input){input=document.createElement('input');input.className='field';input.readOnly=true;input.dataset.kitchenLink='';input.setAttribute('aria-label','رابط مطبخي');box.append(input);}input.value=url.href;input.focus();input.select();showToast('انسخ رابط مطبخك الظاهر.');}}
const settingsWithShare=openKitchenSettings;openKitchenSettings=async function(c){await settingsWithShare(c);document.querySelector('#kitchenSettings .meal-content').append(mealAction('مشاركة مطبخي',()=>shareKitchen(c)));};
async function followKitchenLink(){const match=location.hash.match(/^#kitchen=([0-9a-f-]{36})$/i);if(!match)return;showScreen('chefs');await loadChefs();const c=chefsCache.find(c=>String(c.id)===match[1]);if(c)await openMealOrdering(c);else showToast('هذا المطبخ غير متاح الآن.');}
window.addEventListener('hashchange',()=>followKitchenLink().catch(()=>showToast('تعذر فتح المطبخ.')));followKitchenLink().catch(()=>showToast('تعذر فتح المطبخ.'));

const originalOpenModal=openModal;openModal=function(el){if(el===joinModal){joinGender='';el.querySelectorAll('.gender').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false');});}originalOpenModal(el);};
document.querySelectorAll('.gender').forEach(b=>{b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>document.querySelectorAll('.gender').forEach(x=>x.setAttribute('aria-pressed',String(x===b))));});
