/* Simple launch: one meal creation screen, three kitchen actions, no billing UI. */
'use strict';
document.getElementById('showDiscoveryBtn').onclick=async()=>{showScreen('chefs');await loadChefs();};
document.querySelector('#home .home-form').prepend(document.querySelector('#home .home-paths'));
document.querySelector('#home .chef-invite strong').textContent='حوّلي مهارتك في الطبخ إلى عمل من بيتك.';
document.querySelector('#home .chef-invite p').textContent='اعرضي أطباقك، واطبخي لجيرانك حسب طلبهم.';
document.getElementById('chefLoginBtn')?.remove();
const genderMale=g=>['m','male','ذكر'].includes(String(g||'').toLowerCase());
prefix=g=>genderMale(g)?'عمّي':'أمّي';
const simpleDashboardBase=renderKitchenDashboard;
renderKitchenDashboard=function(c){const screen=simpleDashboardBase(c),box=screen.querySelector('.kitchen-builder');box.querySelector('.builder-step')?.remove();box.querySelector('#myKitchenDishes').hidden=true;box.querySelector('.builder-actions').hidden=true;screen.querySelector('.welcome-kitchen > span').textContent='تم ربط مطبخ منزلك بالمنصة';return screen;};
mountMealDashboard=function(c){const dash=document.getElementById('chefKitchenDashboard'),box=dash.querySelector('.kitchen-builder');let actions=document.getElementById('mealActions');if(!actions){actions=document.createElement('div');actions.id='mealActions';actions.className='simple-kitchen-actions';box.append(actions);}actions.replaceChildren(mealAction('＋ إضافة وجبة',()=>openMealOfferForm(c)),mealAction('وجباتي وطلباتي',openKitchenWork),mealAction('بيانات مطبخي',()=>openKitchenSettings(c)));actions.firstChild.className='primary';};
async function openKitchenWork(){const c=await restoreChefSession(false);if(!c)throw Error('ادخل إلى مطبخك مجددًا.');const screen=mealPanel('kitchenWork','وجباتي وطلباتي'),box=screen.querySelector('.meal-content');box.replaceChildren(mealAction('الطلبات الواردة',openChefMealOrders),mealAction('الوجبات المعروضة',openMyMealOffers));screen.querySelector('.back').onclick=()=>openKitchenDashboard(c);await openChefMealOrders();document.querySelector('#chefMealOrders .meal-content').prepend(mealAction('وجباتي المعروضة',openMyMealOffers));}
async function openKitchenSettings(c){const screen=mealPanel('kitchenSettings','بيانات مطبخي'),box=screen.querySelector('.meal-content');box.innerHTML=`<h1>${prefix(c.gender)} ${escapeHtml(c.name)}</h1><p>${escapeHtml(c.area||'')} · الدار البيضاء</p><p id="kitchenLocationStatus">جاري تحميل الموقع…</p>`;screen.querySelector('.back').onclick=()=>openKitchenDashboard(c);box.append(mealAction('تحديد موقع مطبخي',async()=>{await pickLocation(true,null,saveKitchenPoint);}),mealAction('أيام العمل والاستلام',openKitchenPreferences),mealAction('أطباق مطبخي',openMyMealOffers),mealAction('تسجيل الخروج',async()=>{await mealRpc('chef_logout',{p_session_token:chefSessionToken});localStorage.removeItem(CHEF_SESSION_KEY);chefSessionToken='';currentChefId=null;showScreen('home');}));showScreen(screen.id);try{const p=await mealRpc('chef_location',{p_session_token:chefSessionToken});document.getElementById('kitchenLocationStatus').textContent=p?'موقعك محفوظ. يظهر للزبائن بشكل تقريبي لحماية منزلك.':'حدد الموقع ليجدك الزبائن القريبون. يمكنك فعل ذلك لاحقًا.';if(p){box.append(mealAction('تعديل الموقع',()=>pickLocation(true,[Number(p.lat),Number(p.lng)],saveKitchenPoint)),mealAction('حذف الموقع المحفوظ',async()=>{await mealRpc('chef_location',{p_session_token:chefSessionToken,p_remove:true});await openKitchenSettings(c);}));}}catch{document.getElementById('kitchenLocationStatus').textContent='تعذر تحميل الموقع. يمكنك الاستمرار وتحديده لاحقًا.';}}
async function saveKitchenPoint(p){await mealRpc('chef_location',{p_session_token:chefSessionToken,p_lat:p[0],p_lng:p[1]});const status=document.getElementById('kitchenLocationStatus');if(status)status.textContent='تم حفظ الموقع. يظهر للزبائن بشكل تقريبي.';showToast('تم حفظ موقع مطبخك.');}
function localMealValue(date){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Casablanca',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
async function openMealOfferForm(editOffer=null){if(!editOffer?.dish_name)editOffer=null;const c=await restoreChefSession(false);if(!c)throw Error('ادخل إلى مطبخك مجددًا.');const screen=mealPanel('mealOfferEditor','إضافة وجبة'),box=screen.querySelector('.meal-content'),dishes=normaliseDishes(c.dishes),request=crypto.randomUUID();const defaults=await mealRpc('chef_meal_defaults',{p_session_token:chefSessionToken});screen.querySelector('.back').onclick=()=>openKitchenDashboard(c);
 const specialties=[...document.getElementById('builderSpecialty').options].filter(o=>o.value);
 box.innerHTML=`<form id="mealOfferForm" class="meal-form"><h1>وجبة من مطبخك</h1><label ${c.specialty?'hidden':''}>نوع الأطباق<select name="specialty" class="field" required><option value="">اختيار النوع</option>${specialties.map(o=>`<option ${o.value===c.specialty?'selected':''}>${escapeHtml(o.value)}</option>`).join('')}</select></label>${dishes.length&&!editOffer?`<label>استخدام طبق سابق (اختياري)<select name="saved" class="field"><option value="">طبق جديد</option>${dishes.map((d,i)=>`<option value="${i}">${escapeHtml(d.name)}</option>`).join('')}</select></label>`:''}<label>اسم الوجبة<input name="dish_name" class="field" required maxlength="150" placeholder="مثال: كسكس بالخضر واللحم"></label><label>ثمن الطبق كاملًا بالدرهم<input name="price" class="field" type="number" min="1" max="10000" step="0.01" inputmode="decimal" required></label><label>صورة الوجبة (اختياري)<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" class="field"></label><img id="mealPhotoPreview" alt="معاينة صورة الوجبة" hidden><label>هذا الطبق يكفي<select name="serves_choice" class="field" required><option value="">اختر عدد الأشخاص</option>${Array.from({length:10},(_,i)=>`<option value="${i+1}">${i===0?'شخص واحد':i===1?'شخصان':`${i+1} أشخاص`}</option>`).join('')}<option value="more">أكثر من 10 أشخاص</option></select></label><label id="servesMoreLabel" hidden>عدد الأشخاص بالضبط<input name="serves_more" type="number" class="field" min="11" max="1000" step="1" inputmode="numeric"></label><p id="dishAgreement" aria-live="polite"></p><label>المكونات الرئيسية (اختياري)<textarea name="ingredients" class="field" maxlength="2000" placeholder="مثال: سميد، خضر، لحم"></textarea></label>${defaults?.configured?'<p>تُستخدم إعدادات الاستلام المحفوظة لمطبخك. يمكنك تعديلها من «بيانات مطبخي».</p>':`<section><h2>إعدادات مطبخك — تُحفظ مرة واحدة</h2>${kitchenSettingsFields(defaults||{})}</section>`}<button type="submit" class="primary full" value="done">حفظ والعودة إلى مطبخي</button><button type="submit" class="admin-secondary full" value="another">حفظ وإضافة طبق آخر</button><p role="status" id="mealFormStatus"></p></form>`;
 const form=box.querySelector('form');
 const portionChange=()=>{const more=form.elements.serves_choice.value==='more';box.querySelector('#servesMoreLabel').hidden=!more;form.elements.serves_more.required=more;const n=Number(more?form.elements.serves_more.value:form.elements.serves_choice.value);box.querySelector('#dishAgreement').textContent=n>0&&Number(form.elements.price.value)>0?`طبق واحد يكفي ${peopleLabel(n)}، بثمن إجمالي ${mealMoney(form.elements.price.value)}. طلب طبقين يضاعف العدد والثمن.`:'';};form.elements.serves_choice.onchange=portionChange;form.elements.serves_more.oninput=portionChange;form.elements.price.oninput=portionChange;
 if(!defaults?.configured)bindKitchenSettings(form,defaults||{});
let savedImage=null,uploaded=null,objectUrl=null;const preview=box.querySelector('#mealPhotoPreview');
 if(editOffer){box.querySelector('h1').textContent='تعديل الطبق المعروض';form.elements.specialty.disabled=true;form.elements.dish_name.value=editOffer.dish_name;form.elements.price.value=editOffer.price;form.elements.ingredients.value=editOffer.ingredients||'';form.elements.serves_choice.value=editOffer.serves>10?'more':String(editOffer.serves);form.elements.serves_more.value=editOffer.serves>10?editOffer.serves:'';savedImage=safeImageUrl(editOffer.image_url)||null;if(savedImage){preview.src=savedImage;preview.hidden=false;}form.querySelector('[value=another]').hidden=true;portionChange();}

 if(form.elements.saved)form.elements.saved.onchange=()=>{const d=dishes[Number(form.elements.saved.value)];if(form.elements.saved.value===''){form.elements.dish_name.value='';form.elements.price.value='';savedImage=null;preview.hidden=true;return;}form.elements.dish_name.value=d.name;form.elements.price.value=d.price;savedImage=safeImageUrl(d.image_url)||null;preview.hidden=!savedImage;if(savedImage)preview.src=savedImage;portionChange();};
 form.elements.photo.onchange=()=>{uploaded=null;const f=form.elements.photo.files[0];if(!f)return;if(f.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type)){form.elements.photo.value='';showToast('اختر صورة لا تتجاوز 5 ميغابايت.');return;}if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(f);preview.src=objectUrl;preview.hidden=false;};

 form.onsubmit=e=>{e.preventDefault();if(!form.reportValidity())return;const submitter=e.submitter||form.querySelector('[type=submit]');if(form.dataset.saving)return;form.dataset.saving='1';form.querySelectorAll('[type=submit]').forEach(b=>b.disabled=true);mealBusy(submitter,async()=>{const p=Object.fromEntries(new FormData(form));p.serves=Number(p.serves_choice==='more'?p.serves_more:p.serves_choice);if(!defaults?.configured)Object.assign(p,readKitchenSettings(form));const photo=form.elements.photo.files[0];if(photo&&!uploaded)uploaded=await uploadImageSecure(photo);const dish={name:p.dish_name.trim(),price:Number(p.price),image_url:uploaded||savedImage};if(editOffer)await mealRpc('chef_update_meal',{p_session_token:chefSessionToken,p_offer_id:editOffer.id,p_dish:dish,p_serves:p.serves,p_ingredients:p.ingredients});else await mealRpc('chef_publish_meal',{p_session_token:chefSessionToken,p_dish:dish,p_offer:p,p_request:request});markFormSaved(form);if(objectUrl)URL.revokeObjectURL(objectUrl);showToast('طبقك معروض لاستقبال الطلبات.');if(submitter.value==='another')await openMealOfferForm();else {const fresh=await restoreChefSession(false);if(fresh)await openKitchenDashboard(fresh);}}).finally(()=>{delete form.dataset.saving;form.querySelectorAll('[type=submit]').forEach(b=>b.disabled=false);});};showScreen(screen.id);
};
// Keep saved recipes tucked into settings; the main path never requires saving twice.
const simpleOffersBase=openMyMealOffers;openMyMealOffers=async function(){await simpleOffersBase();document.querySelector('#myMealOffers .meal-content').prepend(mealAction('＋ إضافة وجبة',openMealOfferForm),mealAction('طلبات مطبخي',openChefMealOrders));};
// Order count is separate from how many people each dish serves.
const qty=document.getElementById('mealQuantity'),stepper=document.createElement('div');stepper.className='quantity-stepper';qty.parentNode.insertBefore(stepper,qty);const less=mealAction('−',()=>{}),more=mealAction('+',()=>{});less.setAttribute('aria-label','تقليل عدد الأطباق');more.setAttribute('aria-label','زيادة عدد الأطباق');less.onclick=()=>{qty.value=Math.max(1,Number(qty.value)-1);updateMealTotal();};more.onclick=()=>{qty.value=Math.min(Number(qty.max),Number(qty.value)+1);updateMealTotal();};stepper.append(less,qty,more);
document.getElementById('customerPhone').inputMode='tel';document.getElementById('customerPhone').autocomplete='tel-national';document.getElementById('customerName').autocomplete='given-name';
// Neutral wording works for both male and female cooks without guessing from names.
document.querySelector('#buildKitchen .join-note')?.remove();
// Share a kitchen, never a private order or chef session.
async function shareKitchen(c){const url=new URL(location.origin+location.pathname);url.hash='kitchen='+c.id;const data={title:`${prefix(c.gender)} ${c.name} — أمّي فود`,text:'أطباق مغربية بطعم البيت، من مطبخي إلى بيتك.',url:url.href};try{if(navigator.share){await navigator.share(data);return;}await navigator.clipboard.writeText(url.href);showToast('تم نسخ رابط مطبخك.');}catch(e){if(e.name==='AbortError')return;const box=document.querySelector('#kitchenSettings .meal-content');let input=box.querySelector('[data-kitchen-link]');if(!input){input=document.createElement('input');input.className='field';input.readOnly=true;input.dataset.kitchenLink='';input.setAttribute('aria-label','رابط مطبخي');box.append(input);}input.value=url.href;input.focus();input.select();showToast('انسخ رابط مطبخك الظاهر.');}}
const settingsWithShare=openKitchenSettings;openKitchenSettings=async function(c){await settingsWithShare(c);document.querySelector('#kitchenSettings .meal-content').append(mealAction('مشاركة مطبخي',()=>shareKitchen(c)));};
async function followKitchenLink(){const match=location.hash.match(/^#kitchen=([0-9a-f-]{36})$/i);if(!match)return;showScreen('chefs');await loadChefs();const c=chefsCache.find(c=>String(c.id)===match[1]);if(c)await openMealOrdering(c);else showToast('هذا المطبخ غير متاح الآن.');}
window.addEventListener('hashchange',()=>followKitchenLink().catch(()=>showToast('تعذر فتح المطبخ.')));followKitchenLink().catch(()=>showToast('تعذر فتح المطبخ.'));

const originalOpenModal=openModal;openModal=function(el){if(el===joinModal){joinGender='';el.querySelectorAll('.gender').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false');});}originalOpenModal(el);};
document.querySelectorAll('.gender').forEach(b=>{b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>document.querySelectorAll('.gender').forEach(x=>x.setAttribute('aria-pressed',String(x===b))));});
