const {JSDOM}=require('jsdom');const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script[\s\S]*?<\/script>/g,''),{url:'https://test.invalid',runScripts:'dangerously'}),w=dom.window;
const chef={id:'chef',name:'كريم',gender:'m',specialty:'أكلات تقليدية وشعبية',area:'المعاريف',dishes:[]};const offer={id:'dish',chef_id:'chef',dish_name:'كسكس',price:40,reference_price:40,serves:1,active:true,group_pricing:true,delivery_areas:[]};let request=null;const calls=[];
const settings={configured:true,work_days:'الجمعة',fulfilment_type:'pickup',pickup_instructions:'عنوان خاص'};
const rpc=async(name,args)=>{calls.push([name,args]);switch(name){case 'chef_session_status':return{data:[chef]};case 'chef_meal_defaults':case 'chef_order_settings':return{data:settings};case 'chef_correction_status':return{data:[]};case 'chef_subscription':return{data:{payments:[]}};case 'chef_location':return{data:null};case 'chef_meal_offers':return{data:[offer]};case 'chef_meal_orders':return{data:[]};case 'food_requests_chef':return{data:request?[request]:[]};case 'public_kitchen_locations':return{data:[]};case 'public_kitchen_workdays':return{data:[]};case 'food_request_reputation':return{data:[]};case 'chef_save_reference_dish':return{data:'dish'};
case 'food_request_create':request={id:'request',request_v2:true,order_ref:'OF-test',chef_id:'chef',status:'pending',dish_name:args.p_offer?'كسكس':args.p_customer.dish,people:args.p_people,reference_price:args.p_offer?40:null,estimate:args.p_offer?40*args.p_people:null,requested_at:args.p_customer.requested_at,customer_name:args.p_customer.name,customer_phone:args.p_customer.phone,chef_phone:'0600000001',notes:args.p_customer.notes,agreement_version:0};return{data:{order_ref:'OF-test',estimate:request.estimate}};
case 'food_request_customer':return{data:request};case 'food_request_chef_action':if(args.p_action==='propose'){request={...request,status:'proposed',agreed_dish:args.p_data.dish,agreed_people:Number(args.p_data.people),agreed_total:Number(args.p_data.total),agreed_at:args.p_data.at,agreed_fulfilment:args.p_data.fulfilment,agreement_version:1};}else request.status=args.p_action;return{data:null};
case 'food_request_customer_action':if(args.p_action==='agree'){request.status='accepted';request.customer_agreed_at=new Date().toISOString();}if(args.p_action==='received')request.received_at=new Date().toISOString();if(args.p_action==='rate')request.rating=args.p_data.rating;return{data:null};default:return{error:{message:'unexpected '+name}};}};
const query=table=>({select(){return this},eq(){return this},order(){return Promise.resolve({data:table==='chefs'?[chef]:[offer]})}});
w.supabase={createClient:()=>({rpc,from:query})};w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.confirm=()=>true;w.localStorage.setItem('ommi_chef_session','test');
const errors=[];w.addEventListener('error',e=>errors.push(e.error));
// Real script elements preserve browser strict-mode global binding rules.
for(const file of ['app.js','dish-images.js','meal-orders.js','nearby.js','kitchen-settings.js','simple-launch.js','kitchen-overview.js','food-requests.js']){const script=w.document.createElement('script');script.textContent=fs.readFileSync(path.join(root,file),'utf8');w.document.body.append(script);}
const tick=()=>new Promise(r=>setTimeout(r,25));const clickText=(root,text)=>{const b=[...root.querySelectorAll('button')].find(b=>b.textContent.includes(text));assert.ok(b,'button '+text);b.click();};
(async()=>{
assert.equal(w.eval('mealMoney(40)'), '40 درهمًا');assert.equal(w.eval('mealMoney(40.50)'), '40 درهمًا و50 سنتيمًا');assert.equal(w.eval('mealMoney(3)'), '3 دراهم');
 await w.openMealOfferForm(chef);let f=w.document.getElementById('mealOfferForm');assert.equal(f.elements.serves_choice,undefined);assert.match(f.textContent,/السعر المرجعي للشخص/);f.elements.dish_name.value='غير محفوظ';w.confirm=()=>false;w.document.querySelector('#mealOfferEditor .back').click();assert.equal(w.document.querySelector('.screen.active').id,'mealOfferEditor','unsaved edit retained');w.document.querySelector('#mealOfferEditor .meal-content').click();assert.equal(w.document.querySelector('.screen.active').id,'mealOfferEditor','blank area inert');w.confirm=()=>true;f.elements.dish_name.value='كسكس';f.elements.price.value='40';f.elements.group_pricing.checked=true;f.dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.ok(calls.some(x=>x[0]==='chef_save_reference_dish'&&x[1].p_offer.group_pricing===true));
 await w.openMealOrdering(chef);f=w.document.getElementById('mealCustomerForm');const custom=w.document.getElementById('customDishName');assert.ok(custom&&!custom.hidden);assert.equal(w.document.querySelector('#dishList button').getAttribute('aria-pressed'),'true');f.elements.people.value='5';f.elements.people.dispatchEvent(new w.Event('input',{bubbles:true}));assert.match(w.document.getElementById('requestEstimate').textContent,/200 درهمًا/);assert.doesNotMatch(w.document.getElementById('requestEstimate').textContent,/الإجمالي/);
 custom.value='رفيسة';custom.dispatchEvent(new w.Event('input',{bubbles:true}));assert.match(w.document.getElementById('requestEstimate').textContent,/الثمن بعد الاتفاق/);assert.equal(w.document.querySelector('#dishList button').getAttribute('aria-pressed'),'false');
 f.elements.name.value='زبون اختبار';f.elements.phone.value='0600000002';f.elements.requested_at.value='2030-01-01T12:00';f.dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();let sent=calls.find(x=>x[0]==='food_request_create')[1];assert.equal(sent.p_offer,null);assert.equal(sent.p_people,5);assert.equal(sent.p_customer.dish,'رفيسة');assert.equal(request.estimate,null);
 w.openKitchenDashboard(chef);await tick();assert.match(w.document.getElementById('kitchenOrderCards').textContent,/رفيسة/);clickText(w.document.getElementById('kitchenOrderCards'),'سجّل تفاصيل');f=w.document.querySelector('.agreement-form');f.elements.people.value='3';f.elements.total.value='95';f.elements.fulfilment.value='الاستلام بعد الاتفاق';f.dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(request.status,'proposed');assert.equal(request.people,5);assert.equal(request.agreed_people,3);
 const token=JSON.parse(w.localStorage.getItem('ommi_meal_receipts'))[0].token;await w.openCustomerMealOrder(token);clickText(w.document.querySelector('#customerMealTracking'),'أوافق على');await tick();assert.equal(request.status,'accepted');assert.equal(w.document.querySelector('.request-stars'),null,'no rating before receipt');clickText(w.document.querySelector('#customerMealTracking'),'نعم، استلمت');await tick();assert.ok(w.document.querySelector('.request-stars'));f=w.document.querySelector('.request-stars').closest('form');f.querySelector('input[value="4"]').checked=true;f.dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(request.rating,4);assert.equal(w.document.querySelector('.request-stars'),null,'no duplicate rating UI');
 assert.deepEqual(errors,[]);dom.window.close();console.log('PASS customer-led form, reference estimates, custom request, changed agreement, explicit acceptance, separate receipt and optional single rating');
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
