-- All fixtures and simulated payment confirmations are rolled back.
begin;
do $$
declare c uuid:=gen_random_uuid(); other_chef uuid:=gen_random_uuid(); admin_id uuid;
 payment uuid; payment2 uuid; expiry timestamptz; blocked boolean; offer uuid; response jsonb; order_id uuid;
begin
 select user_id into admin_id from public.admin_users limit 1;
 if admin_id is null then raise exception 'test requires configured administrator'; end if;
 perform set_config('request.jwt.claim.sub','',true);
 blocked:=false;begin perform public.admin_subscriptions();exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL nonadmin';end if;
 insert into public.chefs(id,name,gender,phone,city,status,dishes) values(c,'اختبار الاشتراك','m','0600000010','casablanca','pending','[{"name":"كسكس","price":40}]'),(other_chef,'اختبار منفصل','f','0600000011','casablanca','pending','[]');
 insert into public.chef_sessions(chef_id,token_hash,expires_at) values(c,public._chef_session_hash('subscription-fixture'),now()+interval '1 hour'),(other_chef,public._chef_session_hash('subscription-other'),now()+interval '1 hour');
 update public.subscription_settings set instructions='تعليمات اختبار داخل معاملة متراجعة';
 payment:=public.submit_subscription_payment('subscription-fixture','TEST-'||c::text);
 if payment<>public.submit_subscription_payment('subscription-fixture','TEST-'||c::text) then raise exception 'FAIL repeated claim';end if;
 if public.chef_subscription_valid(c) then raise exception 'FAIL self activation';end if;
 if jsonb_array_length(public.chef_subscription('subscription-other')->'payments')<>0 then raise exception 'FAIL payment privacy';end if;
 blocked:=false;begin perform public.review_subscription_payment(payment,true);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL self confirmation';end if;
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 blocked:=false;begin perform public.review_subscription_payment(payment,true,'',true,false);exception when others then blocked:=true;end;
 if not blocked or (select status from public.subscription_payments where id=payment)<>'pending' then raise exception 'FAIL atomic phone guard';end if;
 perform public.review_subscription_payment(payment,true,'',true,true);
 select paid_until into expiry from public.chefs where id=c;
 if expiry<>now()+interval '1 month' or not public.chef_subscription_valid(c) then raise exception 'FAIL one month';end if;
 perform public.review_subscription_payment(payment,true,'',true,true);
 if expiry<>(select paid_until from public.chefs where id=c) then raise exception 'FAIL double extension';end if;
 payment2:=public.submit_subscription_payment('subscription-fixture','RENEW-'||c::text);
 perform public.review_subscription_payment(payment2,true);
 if (select paid_until from public.chefs where id=c)<>expiry+interval '1 month' then raise exception 'FAIL early renewal';end if;
 insert into public.chef_kitchen_profiles(chef_id,fulfilment_type) values(c,'pickup');
 offer:=public.meal_offer_create('subscription-fixture',0,jsonb_build_object('portion','حصة واحدة','ingredients','خضر','quantity',5,'order_until',now()+interval '1 day','ready_at',now()+interval '2 days','fulfilment_type','pickup','pickup_instructions','عنوان خاص للاختبار'));
 response:=public.place_meal_order(offer,1,'{"name":"اختبار زبون","phone":"0600000012"}','pickup',repeat('e',64));
 if (response->>'total')::numeric<>40 then raise exception 'FAIL commission added';end if;
 select id into order_id from public.orders where order_ref=response->>'order_ref';
 if public.customer_meal_order(repeat('e',64))->>'chef_phone' is null or public.customer_meal_order(repeat('e',64))->>'pickup_instructions' is not null then raise exception 'FAIL contact/address visibility';end if;
 perform public.chef_meal_order_status('subscription-fixture',order_id,'accepted');
 update public.chefs set membership_status='inactive',paid_until=now()-interval '1 second' where id=c;
 if public.chef_subscription_valid(c) then raise exception 'FAIL expiry';end if;
 blocked:=false;begin perform public.place_meal_order(offer,1,'{"name":"اختبار زبون","phone":"0600000013"}','pickup',repeat('f',64));exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL expired booking';end if;
 perform public.chef_meal_order_status('subscription-fixture',order_id,'preparing');
 perform public.chef_meal_order_status('subscription-fixture',order_id,'ready');
 perform public.chef_meal_order_status('subscription-fixture',order_id,'delivered');
 if has_table_privilege('anon','public.subscription_payments','SELECT') or has_table_privilege('authenticated','public.subscription_payments','UPDATE') then raise exception 'FAIL payment grants';end if;
end $$;
rollback;
select 'PASS: fixed 50 MAD, manual authority, isolated claims, atomic activation, idempotency, renewal, expiry, fulfillment, no commission; rolled back' as result;
