const CHEFS=[{id:1,name:'فاطمة الزهراء',prefix:'أمّي',emoji:'👩🏽‍🍳',area:'المعاريف',specialty:'كسكس بالخضر السبع · طاجين الدجاج',story:'وصفات عائلية تطهوها بالطريقة التي تعلمتها من والدتها.',rating:'4.9',time:'12–18 دقيقة',dishes:[['كسكس بالخضر السبع','45 درهم'],['طاجين الدجاج بالزيتون','52 درهم'],['حريرة مغربية','20 درهم']]},{id:2,name:'خديجة',prefix:'أمّي',emoji:'🧕🏽',area:'بوركون',specialty:'رفيسة · بسطيلة · حلويات مغربية',story:'طبخ المناسبات والجمعة، بكميات محدودة حتى يبقى الطبق بيتيًا.',rating:'4.8',time:'15–22 دقيقة',dishes:[['رفيسة بالدجاج البلدي','55 درهم'],['بسطيلة الدجاج','65 درهم'],['سلو منزلي','28 درهم']]},{id:3,name:'مريم',prefix:'أمّي',emoji:'👵🏽',area:'عين السبع',specialty:'طواجن · أطباق شعبية · خبز الدار',story:'مطبخ بسيط وصريح للغداء اليومي، دون اختصار وقت الطهي.',rating:'4.9',time:'10–16 دقيقة',dishes:[['طاجين اللحم بالبرقوق','68 درهم'],['لوبيا على الطريقة المغربية','30 درهم'],['خبز الدار','8 دراهم']]}];
const citySelect=document.getElementById('citySelect'),comingModal=document.getElementById('comingModal'),orderModal=document.getElementById('orderModal'),joinModal=document.getElementById('joinModal'),toast=document.getElementById('toast');let activeChef=null,activeDish=null,joinGender='female';
function showToast(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
function openModal(el){el.classList.add('open');el.setAttribute('aria-hidden','false')}
function closeModal(el){el.classList.remove('open');el.setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.closest('.modal'))));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m)}));
function renderChefs(){const grid=document.getElementById('chefGrid');grid.innerHTML=CHEFS.map(c=>`<article class="chef-card"><div class="chef-image">${c.emoji}</div><div class="chef-content"><div class="chef-name">${c.prefix} ${c.name}</div><div class="chef-story">${c.story}</div><div class="chef-meta"><span>📍 ${c.area}</span><span>★ ${c.rating}</span><span>${c.time}</span></div><div class="chef-story">${c.specialty}</div><button class="chef-button" data-chef="${c.id}">شاهد أطباق ${c.prefix}</button></div></article>`).join('');grid.querySelectorAll('[data-chef]').forEach(b=>b.addEventListener('click',()=>openChef(Number(b.dataset.chef))))}
function openChef(id){activeChef=CHEFS.find(c=>c.id===id);activeDish=null;document.getElementById('orderChefName').textContent=`${activeChef.prefix} ${activeChef.name} · ${activeChef.area}`;const list=document.getElementById('dishList');list.innerHTML=activeChef.dishes.map((d,i)=>`<button class="dish-option" data-dish="${i}"><span>${d[0]}</span><strong>${d[1]}</strong></button>`).join('');list.querySelectorAll('[data-dish]').forEach(b=>b.addEventListener('click',()=>{list.querySelectorAll('.dish-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');activeDish=activeChef.dishes[Number(b.dataset.dish)]}));openModal(orderModal)}
document.getElementById('discoverBtn').addEventListener('click',()=>{const city=citySelect.value;if(!city){showToast('اختر المدينة أولًا');return}if(city!=='casablanca'){const name=citySelect.options[citySelect.selectedIndex].text;document.getElementById('comingTitle').textContent=`${name} · قريبًا`;openModal(comingModal);return}document.getElementById('chefsSection').scrollIntoView({behavior:'smooth'})});
document.getElementById('submitOrderBtn').addEventListener('click',()=>{const name=document.getElementById('customerName').value.trim(),phone=document.getElementById('customerPhone').value.trim(),area=document.getElementById('customerArea').value.trim();if(!activeDish){showToast('اختر طبقًا أولًا');return}if(!name||!phone||!area){showToast('أكمل معلومات الطلب');return}const ref='OF-'+Math.floor(10000+Math.random()*90000);closeModal(orderModal);showToast(`تم تجهيز الطلب ${ref} · سنربطه بقاعدة البيانات في طبقة SaaS`)});
document.querySelectorAll('[data-open-join]').forEach(b=>b.addEventListener('click',()=>openModal(joinModal)));document.querySelectorAll('.gender-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.gender-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');joinGender=b.dataset.gender;updateNamePreview()}));
function cleanName(value){return value.replace(/^(أمّي|امي|أمي|امى|عمّي|عمي|Ommi|Oncle)\s*/i,'').trim()}
function updateNamePreview(){const input=document.getElementById('joinName');const cleaned=cleanName(input.value);if(input.value!==cleaned)input.value=cleaned;document.getElementById('namePreview').textContent=`${joinGender==='female'?'أمّي':'عمّي'} ${cleaned|| (joinGender==='female'?'فاطمة':'كريم')}`}
document.getElementById('joinName').addEventListener('input',updateNamePreview);document.getElementById('submitJoinBtn').addEventListener('click',()=>{const name=cleanName(document.getElementById('joinName').value),phone=document.getElementById('joinPhone').value.trim(),specialty=document.getElementById('joinSpecialty').value.trim();if(!name||!phone||!specialty){showToast('أكمل الاسم والهاتف والتخصص');return}closeModal(joinModal);showToast(`تم تجهيز طلب ${joinGender==='female'?'أمّي':'عمّي'} ${name} للمراجعة`)});document.getElementById('languageBtn').addEventListener('click',()=>showToast('النسخة الفرنسية ستُربط بعد تثبيت النص العربي'));renderChefs();
