-- Simplified launch flow: direct phone/WhatsApp agreement; no second customer approval.
-- Also blocks accepting a request whose requested time has already passed.
-- Runtime function applied in Supabase on 2026-09-18.
-- Current executable correction and actor separation:
-- ../supabase/migrations/20260919232611_direct_contact_consistency.sql
-- Do not reconstruct the function from the historical negotiation migration.
